version: '2'
services:
  flask:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lowercase59%sorry%stop
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
