CREATE TABLE ourValues (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title varchar(255) NOT NULL,
    subtitle varchar(255) NOT NULL,
    descr text NOT NULL
);

--OUR VALUES:
INSERT INTO `ourValues` (`id`,`title`, `subtitle`, `descr`) VALUES ('1','Be yourself','Difference is valued','We believe that diverse ideas, perspectives and backgrounds fuel innovation andbring about a more powerful and creative work environment yielding greater results. We seek to form an inclusive workforce that embraces the diverse communities weserve and in which each person feels confident and enabled to be their true authenticself. Be yourself at work, because that is your best version.');
INSERT INTO `ourValues` (`id`,`title`, `subtitle`, `descr`) VALUES ('2','Be transparent','Open collaboration for truth','We believe that integrity is the foundation for our company on which coworkers buildrelationships, trust, honesty and effective interpersonal relationships. We strive toalways act just and right, work truthfully and honourably, thus maintaining high ethicalstandards, even when no one is watching. We hold ourselves accountable for choiceand outcomes, good as well as bad ones.');
INSERT INTO `ourValues` (`id`,`title`, `subtitle`, `descr`) VALUES ('3','Be customer-centric','Encourage them','We believe in the engagement of customers as a way to create the most efficientsolutions together. We want to build customer relations by creating awareness andresponsible choices that respect the earth and the environment. In partnering withour customers and putting ourselves in their shoes, we can understand their needsand thus deliver the best experience. In doing so we are always open to challengeour ideas of what’s possible.');
INSERT INTO `ourValues` (`id`,`title`, `subtitle`, `descr`) VALUES ('4','Be curious and bold','Strive for excellence','We believe in challenging the status quo. We are passionate about learning and seekto constantly improve and innovate. We are not afraid to make mistakes. Weproactively use them as an opportunity to share and learn. We work to challenge oneanother to push boundaries and think beyond the box to have an impact in thisextraordinary world. Thus, we value original thinking, the passion to attack difficultchallenges, and thoughtful feedback.');
INSERT INTO `ourValues` (`id`,`title`, `subtitle`, `descr`) VALUES ('5','Be sustainable','Embrace it','We believe in the power of technology to enable sustainable progress and minimiseour impact on the environment for the benefit of current and future generations. Westrive for passionate collaborators, who are dedicated to act as environmentaladvocates and to improve the health and happiness of the world. We are committedto incorporate recyclable materials and renewable energy from local sourceswhenever possible. We actively consider the environment in the choices we makeand work towards a more circular economy.');